WIP further andor changes for PLUS
dzenanz/PlusLib pull request #11
Opened 2020-10-21 17:31 UTC by adamaji

It turns out we also want to save the correction files with the raw data as well. Is there any downside to having even more output channels from the andor device (raw, rectified, and dark for both bli and grayscale)? 

WIP because it seems like the plan is for me to work on this with hardware through the end of the week, and if we're not there by then we'll pass the camera back to you next week @dzenanz

2020-10-21 18:53 UTC, dzenanz approved these changes
Using all 4 outputs should be fine. And the new device class architecture inside SonoPlus should make it relatively easy to increase from 2 to 4 channels.

2020-10-21 21:01 UTC, dzenanz requested changes

2020-10-21 21:01 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
> +  AddFrameToDataSource(ds);  // add the dark current to the given data source
The way this is written, this will be the same as raw.

2020-10-21 21:04 UTC, dzenanz requested changes

2020-10-21 21:04 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
Instead, add here:
```cpp
floatImage.convertTo(cvIMG, CV_16UC1);
AddFrameToDataSource(ds);  // add the dark current to the given data source
```

2020-10-22 14:43 UTC, adamaji commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
Doesn't `AcquireFrame` put the acquired frame into the `rawFrame` buffer though? I thought that what is in `floatImage` at that time is the raw image as a result of the `convertTo` operation a few lines before?

I am seeing similar images (perhaps identical, haven't diffed) from the raw channel and the dark channel with and without the change, but I think there's some other issues I'm not seeing since I'm also not hearing the shutter go off after acquiring multiple BLI images and grayscale images seem to return junk or overexposed data (all 65535s)

2020-10-22 15:56 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
I misunderstood what you were trying to do. You want to save the dark current image, not the main image after dark current correction? Then what you are currently doing is fine.

2020-10-22 15:57 UTC, dzenanz approved these changes

2020-10-22 16:00 UTC, adamaji commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
Yes, I'm trying to save all 3, the raw image, the dark current, and the rectified image. We decided to save the darks in case somebody wanted to tweak the corrections after acquisition

2020-10-22 16:06 UTC, dzenanz commented
Merge if you don't plan to push further commits.

2020-10-22 16:08 UTC, dzenanz commented
I assume dark current images depend on the current temperature of the sensor? Otherwise saving them would not make much sense, as they would all look very similar to each other, just with some random noise variations.

2020-10-22 16:09 UTC, adamaji commented
I may need to push some additional commits, I'm currently trying to figure out why the images I'm getting are looking weird here.

Yes, I believe the darks should depend on the current temp of the sensor.

2020-10-26 19:02 UTC, dzenanz approved these changes

2020-10-26 19:02 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
> +  cv::divide(floatImage, cvFlatCorrection, floatImage, 1, CV_32FC1);
Does this fix the rounding to int issue?

2020-10-26 19:15 UTC, adamaji commented on src/PlusDataCollection/Andor/vtkPlusAndorCamera.cxx
> +  cv::divide(floatImage, cvFlatCorrection, floatImage, 1, CV_32FC1);
No, the problem is still there. I made this change when I realized the MasterFlat image needed to be .png instead of .tiff, and the unchanged depth of that image was different and thus the divide needed an explicit output type.

2020-10-26 19:21 UTC, merged